Add a weather api
vasilich99/weather pull request #15
Opened 2021-12-24 17:33 UTC by vasilich99

2021-12-24 22:33 UTC, ivan-podgornov requested changes

2021-12-24 22:33 UTC, ivan-podgornov commented on src/components/big-card/big-card.tsx
> +  weather: Weather | null;
Если в типе указать `weather?: Weather`, получится, что параметр weather необязательный. **Дальше помечу звёздочками коментарий, который относится к этому

2021-12-24 22:33 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +            weather={weatherData.find((item) => city.id === item.id) || null}
**И тогда не придётся делать || null. Можно будет оставить `weatherData.find(...)`

2021-12-24 22:33 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +    const date = `${year} ${month} ${day}`;
Просто запоминай Date.now() и если Date.now() минус то значение что в localStorage даёт в результате больше суток, то делай запрос. Получится более гибкое решение. Если сейчас попросить загружать данные раз в 8 часов - будешь колоссально нравственно страдать. А если хранить Date.now(), таких проблем не будет

2021-12-24 22:33 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +            `http://api.weatherapi.com/v1/current.json?key=${process.env.REACT_APP_WEATHER_KEY}&q=${city.lat},${city.lon}`
Все функции для работы с API, лучше вынести в отдельную папку api. Там же сохранять значения в localStorage. Получится что-то типа `weatherApi.current(cities).then((weather) => setWeatherData(weather))`

2021-12-24 22:35 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +                condition: response.current.condition.text,
Лучше сохранять код condition, а не text. А если ещё использовать в типе enum, будет бомба. enum'ы для этого как раз придумали

2021-12-25 12:35 UTC, vasilich99 commented on src/components/big-card/big-card.tsx
> +  weather: Weather | null;
так рил прикольней

2021-12-27 19:08 UTC, ivan-podgornov requested changes

2021-12-27 19:08 UTC, ivan-podgornov commented on .eslintrc.yml
> +      'endOfLine': 'auto',
Так делать не надо. Ну или если есть аргументы, то можно конечно, но не знаю какие могут быть аргументы

2021-12-27 19:08 UTC, ivan-podgornov commented on src/components/big-card/big-card.tsx
> +                  ? translateWeather(props.weather?.condition)
*translateWeather* неподходящее название. Лучше подойдёт *getIconName*. Ещё используй компонент Icon, а не span. Потому что если поменяется реализация компонента icon, придётся менять реализацию и здесь тоже

2021-12-27 19:08 UTC, ivan-podgornov commented on src/components/big-card/translateWeather.ts
> +  if (rainy.find((item) => item === weatherCondition)) return 'rainy';
Здесь и ниже вместо find лучше использовать includes

2021-12-27 19:08 UTC, ivan-podgornov commented on src/components/weather-app/weather-app.tsx
> +    localStorage.setItem('favourites', JSON.stringify(favourites));
Тут для сохранения в localStorage используется useEffect. Нужно переделать, нужно сделать функцию changeFavouritesHandler, которая будет сохранять города в избранные и вызывать setFavourites

2021-12-27 19:08 UTC, ivan-podgornov commented on src/components/weather-app/weather-app.tsx
> +    if (cards) setFavourites(JSON.parse(cards));
Тут useEffect используется, чтобы получить избранные города из localStorage. useState первым параметром может принимать функцию, которая вернёт значение по умолчанию. Будет лучше именно там получать значение из localStorage, чтобы не делать лишний рендер. Сейчас компонент отрендерится сначала с пустым списком избранных городов, потом выполнится useEffect, который сделает setFavourites и компонент отрендерится ещё раз. Это и есть лишний рендер

2021-12-27 19:56 UTC, vasilich99 commented on .eslintrc.yml
> +      'endOfLine': 'auto',
оно агрилось чето

2021-12-27 20:36 UTC, vasilich99 commented on src/components/weather-app/weather-app.tsx
> +    if (cards) setFavourites(JSON.parse(cards));
Ну нiфiга собi. Я вообще пытался нечто подобное сделать, но не знал, что там функцию может в начале принимать

2021-12-27 20:49 UTC, ivan-podgornov requested changes

2021-12-27 20:49 UTC, ivan-podgornov commented on src/components/big-card/big-card.tsx
> +                props.weather ? getIconName(props.weather?.condition) : 'none'
если weather нет, то и компонент не нужно показывать. Получится:

```
'weather' in props && <Icon name={getIconName(props.weather.condition)} />
```

2021-12-27 20:58 UTC, ivan-podgornov approved these changes

2021-12-27 21:00 UTC, merged