feat: add a filter by condition
vasilich99/weather pull request #27
Opened 2021-12-31 17:49 UTC by vasilich99

2022-01-01 18:29 UTC, ivan-podgornov requested changes

2022-01-01 18:29 UTC, ivan-podgornov commented on src/api/weather.ts
> +  getConditionText(weatherCondition: WeatherCondition) {
В объектах, которые взаимодействуют с api начали появляться методы, которые не относятся к api. Я про translateWindDir, getConditionText. Эти методы относятся к отображению и им нечего делать в объекте, который отправляет запросы

2022-01-01 18:29 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +            if (
Не надо в рендере добавлять условия или какие-то переменные. И тут сильно много итераций, а именно favourites.length * weatherData.length. Можно сделать чтобы количество итераций равнялось weatherData.length. Вообще, это не обязательно на таких маленьких объёмах данных, но нужно уметь это делать. Выше, до return'a добавь useMemo, который возвращает [Map](https://learn.javascript.ru/map-set) в котором id'у города соответствует погода. Это решит сразу две проблемы: внутри рендера не будет функции с телом и итераций станет намного меньше

2022-01-01 18:29 UTC, ivan-podgornov commented on src/components/sort-form/conditions.ts
> +const conditions = [
Лучше сделать это объектом или Map'ом в котором ключу соответствует перевод. Например:

```
const translates = {
  rainy: 'Дождливо',
}
```

Тогда легко можно будет проверить, есть ли перевод для какого-нибудь condition: `condition in translates`, ну и получить перевод можно будет за одну операцию: `translates[condition]` вместо перебора всего массива

2022-01-01 18:29 UTC, ivan-podgornov commented on src/components/sort-form/sort-by-weather-condition.tsx
> +      const conditions = new Set(props.conditions);
Ничоси. Set - это ты сильно. Решение крутое, просто странно что ты на нём остановился. Обычно не используешь такое

2022-01-01 18:29 UTC, ivan-podgornov commented on src/components/sort-form/sort-form.tsx
> +  onChangeConditionQuery: (param: string[]) => void;
Наверное, проп лучше назвать onChangeConditions, потому что query ассоциируется с поисковым запросом, а не с фильтрами

2022-01-01 18:29 UTC, ivan-podgornov commented on src/components/weather-content/weather-content.tsx
> +        conditions={conditionQuery}
ну и соответственно переменную тоже лучше назвать conditions, а не conditionQuery

2022-01-02 22:43 UTC, vasilich99 commented on src/components/sort-form/conditions.ts
> +const conditions = [
Чето странные какие-то советы (или я не понимаю твой замысел), просто зачем мне делать это вместо перебора, если я его для перебора создал? Это же просто чтоб чекбоксы отрисовать
![image](https://user-images.githubusercontent.com/66257346/147891350-5cb2b1a4-ca67-482d-b72d-6719f31e13d3.png)

2022-01-02 23:15 UTC, ivan-podgornov approved these changes

2022-01-02 23:17 UTC, merged