Список городов
vasilich99/weather pull request #9
Opened 2021-12-08 16:15 UTC by vasilich99

2021-12-08 16:56 UTC, ivan-podgornov requested changes
Нужно делать checked кнопку, которая отвечает за тип сортировки. И ещё нужно чтобы работал тот тип сортировки, который сейчас активирован. А то получается, что если я клацну на сортировку от Я до А, и потом клацну ещё раз, оно отсортирует от А до Я. А это немного не то, что ждал пользователь

2021-12-08 16:56 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +  sortParameter: string;
Когда проп называется sortParameter, кажется, что можно отсортировать города по стране, температуре, ещё чему-то. А это на самом деле тип сортировки. Лучше ограничить типы сортировки до 'asc' | 'desc'. Если написать `sortType: 'asc' | 'desc' ;`, не получится передать ничего кроме значений 'asc' и 'desc'

2021-12-08 16:56 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +  const sortedCities = (): City[] => {
Используй тут useMemo. Ну и раз уж ты забываешь использовать useMemo и useCallback, настрой [eslint-плагин](https://github.com/cvazac/eslint-plugin-react-perf), который будет заставлять это делать.

2021-12-08 16:56 UTC, ivan-podgornov commented on src/components/sort-form/sort-by-name.tsx
> +  setSortParameter: (param: string) => void;
пропы должны называться с **on**. Конкретно в этом случае должно быть *onChangeSortType*

2021-12-08 16:56 UTC, ivan-podgornov commented on src/components/sort-form/sort-by-name.tsx
> +  const onChange = useCallback(() => {
Функция, которая будет использоваться как обработчик события должна называться в формате *eventHandler*. В этом случае получится *changeHandler*

2021-12-08 16:56 UTC, ivan-podgornov commented on src/components/sort-form/sort-by-name.tsx
> +      ? props.setSortParameter('desc')
Тернарный оператор предназначен для того чтобы присваивать переменным значения. А тут используется как побочный эффект. Лучше написать так:

```
const invertedType = props.sortType === 'asc' ? 'desc' : 'asc';
props.onChangeSortType(invertedType)
```

2021-12-08 16:56 UTC, ivan-podgornov commented on src/components/weather-content/weather-content.tsx
> +  const [sortParameter, setSortParameter] = useState('asc');
Чтобы здесь в setSortType можно было передать только 'asc' | 'desc', нужно написать:

```
const [sortType, setSortType] = useState<'asc' | 'desc'>('asc');
```

2021-12-08 16:56 UTC, ivan-podgornov commented on src/types.ts
> +  id: number;
Я там не опечатался в issue. Сделай id строкой

2021-12-08 17:00 UTC, ivan-podgornov commented on src/components/sort-form/sort-by-name.tsx
> +      ? props.setSortParameter('desc')
https://learn.javascript.ru/ifelse#netraditsionnoe-ispolzovanie

2021-12-08 19:21 UTC, vasilich99 commented on src/components/cards/cards.tsx
> +  const sortedCities = (): City[] => {
ну мы установили, а он все равно молчит

2021-12-08 19:28 UTC, vasilich99 commented on src/components/cards/cards.tsx
> +  const sortedCities = (): City[] => {
Кстати, почему мемас, а не useCallback?

2021-12-09 10:43 UTC, ivan-podgornov requested changes

2021-12-09 10:43 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +      mainCards.splice(index, 1);
Нельзя менять исходный массив. Нужно создать копию и менять её

2021-12-09 10:43 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +            onChangeFavourite={changeFavouritesHandler}
По названию пропа непонятно что будет происходить. Назови его лучше onAddFavourite, ну и обработчик переименуй в таком случае. onChangeMain тоже непонятно что делает. И есть ощущение, что это лишний проп. Как я понял, когда город попадает в избранное, ты удаляешь его из каталога слева. Лучше прямо в этом компоненте отфильтровать mainCards, чтобы там не было избранных и показать уже этот список городов в каталоге. Понядобится useMemo, который будет зависеть от mainCards и favourites

2021-12-09 10:43 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +  const [favourite, setFavourite] = useState<City[]>([]);
Тут массив, поэтому нужно использовать множественное число

2021-12-09 10:43 UTC, ivan-podgornov commented on src/components/cards/cards.tsx
> +            key={city.name}
В качестве ключа, лучше использовать id

2021-12-09 14:42 UTC, vasilich99 commented on src/components/cards/cards.tsx
> +            onChangeFavourite={changeFavouritesHandler}
а когда удалять буду, еще и onDeleteFavourite сделать что ли?

2021-12-09 14:44 UTC, vasilich99 commented on src/components/cards/cards.tsx
> +            onChangeFavourite={changeFavouritesHandler}
"Лучше прямо в этом компоненте отфильтровать mainCards, чтобы там не было избранных и показать уже этот список городов в каталоге" - ниче не пон

2021-12-09 16:13 UTC, ivan-podgornov approved these changes

2021-12-09 16:15 UTC, merged